docker_image:
  default: smartbugs/smartcheck
cmd: -p
info: Securify automatically checks for vulnerabilities and bad coding practices. It runs lexical and syntactical analysis on Solidity source code.
